### ISSUE TITLE
Support group view?

### ISSUE THREAD

**Issue by Alias-z** [yatengLG/ISAT_with_segment_anything#33]
Hi, I tried to modify the code to visualize polygons belonging to the same group. Yet I am not skillful enough to do so...

If you find this potentially convenient as well, could you please provide a guide to achieve this? Thx!

**Comment by yatengLG** [comment]
If you need a function  to visualize polygons belonging to the same group similar to visualize single polygon.

You need update mainwindow UI, and add a new dock, to show group id.

1. Update UI
  * You need change Maindow.ui with QT designer, add a ```group dock```.
      https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/ui/MainWindow.ui

  * Add a group dock widget UI, i think you can use the code with renamed it.
      https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/ui/label_dock.py

2. update widget

* Renamed [this file](https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/widgets/labels_dock_widget.py
) and change it with following advice.

You can create a new widgets to show group id, this window will same as labels dock. The code detail you can refer to 
https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/widgets/labels_dock_widget.py

The function ```right_button_menu``` is not needed. 

In function ```generate_item_and_itemwidget```, you can change layout only keep ```check_box``` and ```group```.

In function ```update_listwidget```, only process group once, rather than all polygon.

The function ```set_selected``` and ```set_polygon_selected```, you need delete. These functions is incompatible, software **only support edit single polygon and select single polygon at same time**.

In function ```set_polygon_show```, you need update code from single polygon to polygons.

* Add group dock widget to mainwindow, 
 https://github.com/yatengLG/ISAT_with_segment_anything/blob/7e2b31bedfac500d38e0c80db972410733cfc62d/widgets/mainwindow.py#L93

**Comment by Alias-z** [comment]
> If you need a function to visualize polygons belonging to the same group similar to visualize single polygon.
> 
> You need update mainwindow UI, and add a new dock, to show group id.
> 
> 1. Update UI
> 
> * You need change Maindow.ui with QT designer, add a `group dock`.
>   https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/ui/MainWindow.ui
> * Add a group dock widget UI, i think you can use the code with renamed it.
>   https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/ui/label_dock.py
> 
> 2. update widget
> 
> * Renamed [this file](https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/widgets/labels_dock_widget.py) and change it with following advice.
> 
> You can create a new widgets to show group id, this window will same as labels dock. The code detail you can refer to https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/widgets/labels_dock_widget.py
> 
> The function `right_button_menu` is not needed.
> 
> In function `generate_item_and_itemwidget`, you can change layout only keep `check_box` and `group`.
> 
> In function `update_listwidget`, only process group once, rather than all polygon.
> 
> The function `set_selected` and `set_polygon_selected`, you need delete. These functions is incompatible, software **only support edit single polygon and select single polygon at same time**.
> 
> In function `set_polygon_show`, you need update code from single polygon to polygons.
> 
> * Add group dock widget to mainwindow,
>   https://github.com/yatengLG/ISAT_with_segment_anything/blob/7e2b31bedfac500d38e0c80db972410733cfc62d/widgets/mainwindow.py#L93

Thanks a lot for your patience and informative response. I will try to figure it out, and probably a PR if I manage to do it :)
