### ISSUE TITLE
Problems with the generated polygons

### ISSUE THREAD

**Issue by fremk** [yatengLG/ISAT_with_segment_anything#56]
Hello, thank you for your great contribution to the image segmentation scene.
I noticed while trying your tool that if there are masks, generated by SAM, that have holes in them (or areas that are detached from each other), the polygon generated at the end is fully filled and does not have the hole in it (or the polygon keeps only one of the areas instead of all the areas).

For example if there is a ball in the middle of a green field and I segment the green field, the mask generated by SAM is correct (it doesn't contain the ball) but the polygon generated at the end contains the ball. 

These might be exceptions that you didn't take into consideration,
thank you nonetheless for the great project!
Karim.

**Comment by yatengLG** [comment]
I'm sorry for causing you confusion.I'm so lazy that the English explanation hasn't been updated yet.

Your problem have be solved in newest update.

The reason for this problem is Polygon can't deal with the mask that holes in it, but i must use polygon to show segment result for keep them can be edit.

In newest update, the function of convert mask to polygon has been updated. Now you can select 'max only', 'external' or 'all'  to choice you need way.

'max only' will only save the max polygon when SAM mask have areas that are detached from each other.
'external' will only save external polygons,Internal polygons will not save.
'all' will save all polygons whether internal or external.**Polygon still can't deal with the mask that holes in it.Now will be added polygons in these holes.**

Use your example,there is a ball in the middle of a green field.You segment the green field, now you will get two polygons, one polygon contains the ball and the green field, other polygon contains the ball only.And category of the polygon only contains the ball is background.

https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/docs/功能说明.md#3轮廓保存模式
